on:
  push:

name: slash-star-to-markdown

jobs:
  rendermd:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed
         
      - name: Get git diffs
        id: diffs
        run:
          echo ::set-output name=GIT_DIFFS::$(git diff-tree --no-commit-id --name-only -r HEAD)

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.diffs.outputs.GIT_DIFFS }}"

      - name: Update documentation
        run: |
          echo ${{ steps.diffs.outputs.GIT_DIFFS }}
          python .github/workflows/slash-star-to-markdown.py ${{ steps.diffs.outputs.GIT_DIFFS }}

      - name: Commit and push changes	
        run: |
          git diff
          git config --global user.email "slash-star-to-md@bot.com"	
          git config --global user.name "slash-star-to-md-action"
          git add \*.md
          git diff-index --quiet HEAD  || (git commit -m "Updated documentation")
          git push
