on:
  push:

name: slash-star-to-markdown

jobs:
  rendermd:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed

      - name: run python
        run: |
          python .github/workflows/slash-star-to-markdown.py

      - name: Commit and push changes	
        run: |
          git diff
          git config --global user.email "slash-star-to-md@bot.com"	
          git config --global user.name "slash-star-to-md-action"
          git add \*.md
          git diff-index --quiet HEAD  || (git commit -m "Updated documentation")
          git push
